### ISSUE TITLE
Автоматическая выгрузка данных. Логин.

### ISSUE THREAD

**Issue by AndreyN-SanCity** [1CGoods/ModuleFor1C#21]
При автоматической выгрузке данных, в поле "Логин" возвращать уведомление, что выгрузка сделана регламентным заданием.

**Comment by AndreyN-SanCity** [comment]
![image](https://user-images.githubusercontent.com/34026602/33664883-2f56f362-daa6-11e7-85b5-091044a8f26d.png)

**Comment by DAKopylov** [comment]
![image](https://user-images.githubusercontent.com/34026526/33818020-c0fdf6d4-de53-11e7-827b-71937e9b3a62.png)
Только что проверял, все работает

**Comment by AndreyN-SanCity** [comment]
![image](https://user-images.githubusercontent.com/34026602/33818194-91bf5eb6-de54-11e7-9027-07aec1451cf7.png)
У кого нет, пользуются старыми версиями обработки?

**Comment by DAKopylov** [comment]
ну вероятно11.12.2017, 09:21, "Andrey" <notifications@github.com>:
У кого нет, пользуются старыми версиями обработки?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




С уважением,Копылов ДмитрийООО "Сан-сити"8 (862) 227-00-10 доб. 218dmitryk@san-city.info

**Comment by AndreyN-SanCity** [comment]
Переношу в выполненные

 

С уважением,

Андрей Добриченко

--

andreyn@san-city.info | офис +7(495) 111 00 10 | сот. +7(928) 4579979 | skype: andrey.san-city
